import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"

const pop = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "800"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={pop.className + "bg-black text-white"}>{children}</body>
    </html>
  )
}
